### ISSUE TITLE
edge values pos_edge_data[x][y]<y

### ISSUE THREAD

**Issue by EthanYeoh** [liyongqi67/ALPINE#1]
Hi, 
I have read your paper and I am very interested in your work.
In the microvideo dataset, I find that, in pos_edge_data and neg_edge_data, some items are linked to following items but not preceding items. 
If I am not wrong, pos_edge_data[x][y] should be less than y, and analogy for neg_edge_data. In some cases (most happens in the first few elements), the values of edge_data don't follow this rule. Is this a trick not explained in paper? Or would you explain this issue?
Thanks & BR,
Ethan

**Comment by liyongqi67** [comment]
Hello Ethan,
    The first item is linked to itself because there are no preceding items. And the second item is linked to the first item because there is only one preceding item. I just uploaded the code for the pos_edge_data and neg_edge_data generation, which you can refer to. 
Yongqi
