### ISSUE TITLE
Data access

### ISSUE THREAD

**Issue by NadineKroher** [liyongqi67/ALPINE#3]
Thanks for sharing this nice implementation! My team is currently working on a similar problem and it would help us a lot to run your method. Is there any alternative way of getting access to the dataset? Baidu seems to require a mainland chinese mobile phone to create an account...

**Comment by liyongqi67** [comment]
Ok. I will try to upload the data to dropbox or google drive and it will take some time.

**Comment by liyongqi67** [comment]
Hello, I have uploaded Dataset I to google drive(https://drive.google.com/drive/folders/1KEgF2LgXbOlAlidRB56S5iOZf80sWEy2?usp=sharing). As for Dataset II, it is released at https://github.com/Ocxs/THACIL, and you can contact them to download it.

**Comment by liyongqi67** [comment]
I'm closing this for now. Feel free to reopen/open a new issue if there are further questions!
