### ISSUE TITLE
数据集获取

### ISSUE THREAD

**Issue by ydcs1** [liyongqi67/ALPINE#4]
学长您好，我不小心误覆盖了数据集，然后想重新下载，发现原来那个网站的数据集没有了。能不能在那个网站重新上传一下，非常感谢！！！

**Comment by liyongqi67** [comment]
[Dataset I](https://pan.baidu.com/s/1iysBGLe4QVFGJuVp-WOfrQ), [Dataset II](https://github.com/Ocxs/THACIL).

**Comment by liyongqi67** [comment]
I'm closing this for now. Feel free to reopen/open a new issue if there are further questions!

**Comment by ydcs1** [comment]
ok，thank you very much！
