### ISSUE TITLE
一些关于数据集含义的问题

### ISSUE THREAD

**Issue by Mike-debug** [liyongqi67/ALPINE#5]
请问作者
1.dataset.pkl中train_interaction_data为list类型，每个元素为tupple类型，每个tupple含有三个元素，请问每个tupple中后两个元素是什么含义，比如([1248, 142071, 0, 0, 0, 760996840369, 0, 17], 35, 65)中，35和65什么含义
2.dataset.pkl中pos_his_data、neg_his_data、pos_edge_data和neg_edge_data代表什么含义，pos_edge_data和neg_edge_data中的值为一些列表，这些列表中的元素是什么含义，我发现最大是297，最小是0，而且pos_his_data和pos_edge_data相等的键对应的列表长度是相等的，这是什么含义
3.user_like.npy是什么含义，为什么有负整数
visual64_select.npy是什么含义，依据什么分布
4.请问作者有没有用户兴趣大赛的原始数据https://www.kesci.com/home/competition/5ad306e633a98340e004f8d1/content/3
我得到的数据是经过您预处理的

**Comment by liyongqi67** [comment]
1 分别是positive_history和negative_history的长度，用这两个数字取出当前video之前的history
2 pos_his_data，neg_his_data分别是储存video的positive_history和negative_history
   pos_edge_data和neg_edge_data分别储存对一个sequence history中的每一个video除了sequence的前一个video，所链接的另一个video
3 user_like是利用用户的点赞和follow的视频预训练的user embedding
4 原始数据请联系大赛组委会，我论文的数据是原始数据的一个随机子集

**Comment by Mike-debug** [comment]
![image](https://user-images.githubusercontent.com/57356379/94225007-74b3c500-ff26-11ea-81ce-91011865bc10.png)
请问作者，user_like和visual64_select描述的特征是user和photo本身的性质，还是user和photo喜欢与被喜欢的交互性质，这两个npy相关还是独立

**Comment by liyongqi67** [comment]
1 visual64_select是photo本身的视觉特征，user_like是user喜欢和follow的video的视觉特征的平均，但很多user可能没有喜欢和follow的视频，所以这个特征很稀疏
2 我打印了一下visual64_select的数据，和你贴的不一样啊
(3242315, 64)
[[-0.59202386 -2.68790455  1.50158656  0.52942338 -1.00612201  0.46149524
  -1.35391053 -0.20962497 -0.89667332  0.13331173  1.67896185  0.76402228
   1.08538235 -1.97132914  2.47873126  0.4387426   1.15909447  0.03185664
   0.59059984 -0.66402744  0.87211278 -0.13188915  1.04258856 -1.8153512
   0.57990245  0.41382896  1.81684758 -0.54757217  0.51196574  0.40130824
   0.34514311 -1.24528101 -0.03707205 -0.94805994 -0.30337162  1.08888382
  -0.32165332 -0.55207816 -0.14796771 -0.15973056 -0.67603386 -1.25163107
   0.26783786  0.14703784  0.64612669  0.31014603  0.03085806 -0.56633214
   0.65754971 -0.7917947  -0.69127473  0.87453925 -0.03051719 -0.85384869
  -0.39369436  0.14925323 -0.16816293  0.9217901  -0.27917553 -0.64888138
   0.10428962  0.35051853 -0.89023439  1.21799864]
 [-1.56206093 -3.28017906 -0.97322222  0.15520673 -0.92630734 -0.58027076
  -1.76760916 -1.19270798  0.22275552 -0.36853774  1.05160763  0.70612311
  -0.77559683 -0.80028013  0.69124845 -1.32974179  0.43319472 -1.59980668
  -1.23404507  0.18505058 -0.15394037 -1.18870662 -0.28332183  0.50023386
  -0.39776167  0.57964556 -1.461375    0.21716546 -0.11123578 -0.09168229
  -0.58523147 -2.66593406 -0.018949   -0.57791808 -0.37766186  0.62965696
   0.89142186  0.29458578 -0.7294171   1.03989688  1.45723743 -0.36099593
   0.1915524  -0.21367659  0.46579716 -0.03641252 -0.31028204 -0.25946227
   1.25264018  0.66687165  0.71976808 -0.77137514 -0.4861523   0.2730559
  -1.00834068  0.45262665  0.18659997  0.37975369 -0.24002365 -0.9970235
   0.31783574 -1.02061632 -1.30222362  0.79804922]]

**Comment by liyongqi67** [comment]
1 visual64_select是photo本身的视觉特征，user_like是user like以及follow的video的视觉特征的平均值
2 我看你visual64_select的打印去check了一下，visual64_select[99:101]如下，和你贴出来的不一样，应该是你打印错了？：
[[-0.59202386 -2.68790455  1.50158656  0.52942338 -1.00612201  0.46149524
  -1.35391053 -0.20962497 -0.89667332  0.13331173  1.67896185  0.76402228
   1.08538235 -1.97132914  2.47873126  0.4387426   1.15909447  0.03185664
   0.59059984 -0.66402744  0.87211278 -0.13188915  1.04258856 -1.8153512
   0.57990245  0.41382896  1.81684758 -0.54757217  0.51196574  0.40130824
   0.34514311 -1.24528101 -0.03707205 -0.94805994 -0.30337162  1.08888382
  -0.32165332 -0.55207816 -0.14796771 -0.15973056 -0.67603386 -1.25163107
   0.26783786  0.14703784  0.64612669  0.31014603  0.03085806 -0.56633214
   0.65754971 -0.7917947  -0.69127473  0.87453925 -0.03051719 -0.85384869
  -0.39369436  0.14925323 -0.16816293  0.9217901  -0.27917553 -0.64888138
   0.10428962  0.35051853 -0.89023439  1.21799864]
 [-1.56206093 -3.28017906 -0.97322222  0.15520673 -0.92630734 -0.58027076
  -1.76760916 -1.19270798  0.22275552 -0.36853774  1.05160763  0.70612311
  -0.77559683 -0.80028013  0.69124845 -1.32974179  0.43319472 -1.59980668
  -1.23404507  0.18505058 -0.15394037 -1.18870662 -0.28332183  0.50023386
  -0.39776167  0.57964556 -1.461375    0.21716546 -0.11123578 -0.09168229
  -0.58523147 -2.66593406 -0.018949   -0.57791808 -0.37766186  0.62965696
   0.89142186  0.29458578 -0.7294171   1.03989688  1.45723743 -0.36099593
   0.1915524  -0.21367659  0.46579716 -0.03641252 -0.31028204 -0.25946227
   1.25264018  0.66687165  0.71976808 -0.77137514 -0.4861523   0.2730559
  -1.00834068  0.45262665  0.18659997  0.37975369 -0.24002365 -0.9970235
   0.31783574 -1.02061632 -1.30222362  0.79804922]]
3 我去check了一下user_like的数据，是我上传错误了，十分感谢你的提问，我现在更新了user_like的数据

十分感谢您的提问

**Comment by Mike-debug** [comment]
你好，请问您更新后的alpine的数据集有下载方式吗，我没有在github上找到
另外就是想问下，user本身是不是只有userid一个特征，因为其他特征都是交互特征



魏一鸣
Yiming Wei
浙江大学计算机科学与技术学院
College of Computer Science and Technology of Zhejiang University
Email:1781937775@qq.com
Tel:(+86)136-6575-6920


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liyongqi67/ALPINE"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月27日(星期天) 下午2:48
收件人:&nbsp;"liyongqi67/ALPINE"<ALPINE@noreply.github.com&gt;;
抄送:&nbsp;"魏一鸣"<1781937775@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liyongqi67/ALPINE] 一些关于数据集含义的问题 (#5)





 
1 visual64_select是photo本身的视觉特征，user_like是user like以及follow的video的视觉特征的平均值
 2 我看你visual64_select的打印去check了一下，visual64_select[99:101]如下，和你贴出来的不一样，应该是你打印错了？：
 [[-0.59202386 -2.68790455  1.50158656  0.52942338 -1.00612201  0.46149524
 -1.35391053 -0.20962497 -0.89667332  0.13331173  1.67896185  0.76402228
 1.08538235 -1.97132914  2.47873126  0.4387426   1.15909447  0.03185664
 0.59059984 -0.66402744  0.87211278 -0.13188915  1.04258856 -1.8153512
 0.57990245  0.41382896  1.81684758 -0.54757217  0.51196574  0.40130824
 0.34514311 -1.24528101 -0.03707205 -0.94805994 -0.30337162  1.08888382
 -0.32165332 -0.55207816 -0.14796771 -0.15973056 -0.67603386 -1.25163107
 0.26783786  0.14703784  0.64612669  0.31014603  0.03085806 -0.56633214
 0.65754971 -0.7917947  -0.69127473  0.87453925 -0.03051719 -0.85384869
 -0.39369436  0.14925323 -0.16816293  0.9217901  -0.27917553 -0.64888138
 0.10428962  0.35051853 -0.89023439  1.21799864]
 [-1.56206093 -3.28017906 -0.97322222  0.15520673 -0.92630734 -0.58027076
 -1.76760916 -1.19270798  0.22275552 -0.36853774  1.05160763  0.70612311
 -0.77559683 -0.80028013  0.69124845 -1.32974179  0.43319472 -1.59980668
 -1.23404507  0.18505058 -0.15394037 -1.18870662 -0.28332183  0.50023386
 -0.39776167  0.57964556 -1.461375    0.21716546 -0.11123578 -0.09168229
 -0.58523147 -2.66593406 -0.018949   -0.57791808 -0.37766186  0.62965696
 0.89142186  0.29458578 -0.7294171   1.03989688  1.45723743 -0.36099593
 0.1915524  -0.21367659  0.46579716 -0.03641252 -0.31028204 -0.25946227
 1.25264018  0.66687165  0.71976808 -0.77137514 -0.4861523   0.2730559
 -1.00834068  0.45262665  0.18659997  0.37975369 -0.24002365 -0.9970235
 0.31783574 -1.02061632 -1.30222362  0.79804922]]
 3 我去check了一下user_like的数据，是我上传错误了，十分感谢你的提问，我现在更新了user_like的数据
 
十分感谢您的提问

**Comment by Mike-debug** [comment]
你好，请问您更新后的alpine的数据集有下载方式吗，我没有在github上找到
另外就是想问下，user本身是不是只有userid一个特征，因为其他特征都是交互特征


请问您有大赛的源数据吗

魏一鸣
Yiming Wei
浙江大学计算机科学与技术学院
College of Computer Science and Technology of Zhejiang University
Email:1781937775@qq.com
Tel:(+86)136-6575-6920


&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "liyongqi67/ALPINE"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月27日(星期天) 下午2:48
收件人:&nbsp;"liyongqi67/ALPINE"<ALPINE@noreply.github.com&gt;;
抄送:&nbsp;"魏一鸣"<1781937775@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liyongqi67/ALPINE] 一些关于数据集含义的问题 (#5)





 
1 visual64_select是photo本身的视觉特征，user_like是user like以及follow的video的视觉特征的平均值
 2 我看你visual64_select的打印去check了一下，visual64_select[99:101]如下，和你贴出来的不一样，应该是你打印错了？：
 [[-0.59202386 -2.68790455  1.50158656  0.52942338 -1.00612201  0.46149524
 -1.35391053 -0.20962497 -0.89667332  0.13331173  1.67896185  0.76402228
 1.08538235 -1.97132914  2.47873126  0.4387426   1.15909447  0.03185664
 0.59059984 -0.66402744  0.87211278 -0.13188915  1.04258856 -1.8153512
 0.57990245  0.41382896  1.81684758 -0.54757217  0.51196574  0.40130824
 0.34514311 -1.24528101 -0.03707205 -0.94805994 -0.30337162  1.08888382
 -0.32165332 -0.55207816 -0.14796771 -0.15973056 -0.67603386 -1.25163107
 0.26783786  0.14703784  0.64612669  0.31014603  0.03085806 -0.56633214
 0.65754971 -0.7917947  -0.69127473  0.87453925 -0.03051719 -0.85384869
 -0.39369436  0.14925323 -0.16816293  0.9217901  -0.27917553 -0.64888138
 0.10428962  0.35051853 -0.89023439  1.21799864]
 [-1.56206093 -3.28017906 -0.97322222  0.15520673 -0.92630734 -0.58027076
 -1.76760916 -1.19270798  0.22275552 -0.36853774  1.05160763  0.70612311
 -0.77559683 -0.80028013  0.69124845 -1.32974179  0.43319472 -1.59980668
 -1.23404507  0.18505058 -0.15394037 -1.18870662 -0.28332183  0.50023386
 -0.39776167  0.57964556 -1.461375    0.21716546 -0.11123578 -0.09168229
 -0.58523147 -2.66593406 -0.018949   -0.57791808 -0.37766186  0.62965696
 0.89142186  0.29458578 -0.7294171   1.03989688  1.45723743 -0.36099593
 0.1915524  -0.21367659  0.46579716 -0.03641252 -0.31028204 -0.25946227
 1.25264018  0.66687165  0.71976808 -0.77137514 -0.4861523   0.2730559
 -1.00834068  0.45262665  0.18659997  0.37975369 -0.24002365 -0.9970235
 0.31783574 -1.02061632 -1.30222362  0.79804922]]
 3 我去check了一下user_like的数据，是我上传错误了，十分感谢你的提问，我现在更新了user_like的数据
 
十分感谢您的提问

**Comment by liyongqi67** [comment]
https://github.com/liyongqi67/ALPINE  页面下面的Dataset I，我已经更新了

**Comment by Mike-debug** [comment]
抱歉我这看不到







魏一鸣
Yiming Wei
浙江大学计算机科学与技术学院
College of Computer Science and Technology of Zhejiang University
Email:1781937775@qq.com
Tel:(+86)136-6575-6920


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liyongqi67/ALPINE"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月27日(星期天) 下午5:03
收件人:&nbsp;"liyongqi67/ALPINE"<ALPINE@noreply.github.com&gt;;
抄送:&nbsp;"魏一鸣"<1781937775@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liyongqi67/ALPINE] 一些关于数据集含义的问题 (#5)





 
https://github.com/liyongqi67/ALPINE页面下面的Dataset I，我已经更新了

**Comment by liyongqi67** [comment]
1 https://github.com/liyongqi67/ALPINE 页面下面的Dataset I（https://pan.baidu.com/s/1iysBGLe4QVFGJuVp-WOfrQ#list/path=%2F），我更新了里面的user_like.npy, 大小是2.4M
2 user本身只有userid一个特征
3 没有大赛原数据，如果需要请联系大赛组委会

**Comment by Mike-debug** [comment]
之前问过您一个问题：
1.dataset.pkl中train_interaction_data为list类型，每个元素为tupple类型，每个tupple含有三个元素，请问每个tupple中后两个元素是什么含义，比如([1248, 142071, 0, 0, 0, 760996840369, 0, 17], 35, 65)中，35和65什么含义
我今天验证了一下，遇到了一些问题
这个记录说的是：user1248不喜欢photo142071，之前的历史数据中有35个喜欢的视频，65个不喜欢的视频
![image](https://user-images.githubusercontent.com/57356379/94691760-4558ea00-0364-11eb-939e-c2d4bdfaa541.png)
但是在neg的历史数据中找到的位置是72
![image](https://user-images.githubusercontent.com/57356379/94691767-4a1d9e00-0364-11eb-9736-795b356b13b1.png)

其他的一些记录或者找不到或者位置不对这是为什么

**Comment by liyongqi67** [comment]
感谢您的提问
1) 对于用户所有的历史信息序列，如果长度>300, 我们会进行随机删除，也就是说，本来用户与某个photo的交互的历史信息的长度为n，但我们只用了其中的一部分。尤其是对于neg_his_data，平均长度达到了900，是pos_his_data的三倍，因此很多neg_his_data需要删除，因为对序列长度的处理能力是有限的
The length of users’ historical sequence is set to 300. If it exceeds 300, we truncated it to 300
2） 同一个用户和不同photo交互的时间戳有可能是同样的，对于这种，我们定义的某个交互的history是time<当前交互的time

**Comment by liyongqi67** [comment]
我先把这个issue关了哈，如果有什么问题再随时提问，感谢你的问题
