### ISSUE TITLE
数据集的其他模态信息

### ISSUE THREAD

**Issue by libeibei95** [liyongqi67/ALPINE#6]
作者你好，我对您的工作很感兴趣，您的开源代码和数据集也对我的研究有非常大的帮助。

不过，Dataset I 除了视觉信息，您是否可以也开放下文本、人脸等其他模态信息呢？

谢谢

李贝贝
中科院软件所
libeibei16@otcaix.iscas.ac.cn

**Comment by liyongqi67** [comment]
你好，我们工作中的数据集来源于 “用户兴趣建模”比赛。但原始数据太大，我们只保留了我们工作需要的部分。如果您对整个数据集有兴趣，可以看一下能不能在其他地方下载。
