### ISSUE TITLE
Kuaishou Competition dataset (Dataset I)

### ISSUE THREAD

**Issue by fireflyHunter** [liyongqi67/ALPINE#7]
According to the official page of Kuaishou Competition dataset, there is a text description for each micro-video. However this piece of information is missing from the link provided in this GitHub repo. Is the text description of this dataset available for download?

**Comment by liyongqi67** [comment]
The text information is not contained in our data since our work did not utilize the text input. I am sorry.

**Comment by fireflyHunter** [comment]
Could you maybe direct me to the right place to download this dataset with text descriptions?

**Comment by liyongqi67** [comment]
This is the link to kuaishou competition (https://www.heywhale.com/home/competition/5ad306e633a98340e004f8d1).  The competition was completed, so I don't know whether the data can be downloaded or not. Maybe you can contact the organizers.
